#!/usr/bin/env bash
# Install nginx
sudo apt-get update -y
sudo apt-get install nginx -y
echo "Hello World!" > /var/www/html/index.nginx-debian.html
conf="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch\?v=QH2-TGUlwu4 permanent;"
sudo sed -i "s/server_name _;/$conf/" /etc/nginx/sites-available/default
sudo service nginx restart
