#!/usr/bin/env bash
# Install nginx
sudo apt-get update -y
sudo apt-get install nginx -y
echo "Ceci n'est pas une page" > /var/www/html/404.html
echo "Hello World!" > /var/www/html/index.nginx-debian.html
conf="\tlocation /redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch\?v=QH2-TGUlwu4;\n\t}"
err="\n\\terror_page 404 /404.html;\n\tlocation = /var/www/html/404.html {\n\t\tinternal;\n\t}"
sudo sed -i "s/server_name _;/$conf/" /etc/nginx/sites-available/default
sudo sed -i "s/server_name _;/$err/" /etc/nginx/sites-enabled/default
sudo service nginx restart
