#!/usr/bin/env bash
# Programs that are detached from the terminal and running in the background are called daemons or processes
# need to be managed. The general minimum set of instructions is: start, restart and stop. The most popular way
# of doing so on Unix system is to use the init scripts.

if [ "$1" == "start" ]
then
    bash ./manage_my_process &
    echo $$ > /var/run/my_process.pid
    echo "manage_my_process started"

elif [ "$1" == "stop" ]
then
    pkill -f ./manage_my_process
    rm /var/run/my_process.pid
    echo "manage_my_process stopped"

elif [ "$1" == "restart" ]
then
    pkill -f ./manage_my_process
    rm /var/run/my_process.pid
    bash ./manage_my_process &
    echo $$ > /var/run/my_process.pid
    echo "manage_my_process restarted"

else
  echo "Usage: manage_my_process {start|stop|restart}"
fi

